# Generated by Django 4.2.30 on 2026-07-30 08:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("city", models.CharField(max_length=50)),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("SCHOOL", "Школа"),
                            ("KINDERGARTEN", "Детский сад"),
                            ("FREE_SCHOOL", "Бесплатная школа (ГЧП)"),
                            ("CREATIVE", "Креативные индустрии"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_free", models.BooleanField(default=False)),
                (
                    "subsidy_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "shares_pricing_with",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.branch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "grade_or_group",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "grade_band",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRESCHOOL", "0 класс"),
                            ("PRIMARY_SECONDARY", "1-11 класс"),
                            ("SENIOR", "12 класс"),
                        ],
                        max_length=30,
                    ),
                ),
                ("allergies", models.TextField(blank=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("is_second_child", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("iin", models.CharField(blank=True, max_length=12)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("PARENT", "Родитель"),
                            ("B2B_REPRESENTATIVE", "Представитель компании"),
                        ],
                        default="PARENT",
                        max_length=30,
                    ),
                ),
                ("has_subsidy", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_food", models.BooleanField(default=False)),
                ("has_transport", models.BooleanField(default=False)),
                (
                    "transport_zone",
                    models.CharField(
                        blank=True,
                        choices=[("CITY", "Город"), ("SUBURB", "Пригород")],
                        max_length=20,
                    ),
                ),
                (
                    "contract_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("discount_percent", models.PositiveIntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Активна"),
                            ("WON", "Выиграна"),
                            ("LOST", "Проиграна"),
                            ("WAITLIST", "Лист ожидания"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_cross_branch", models.BooleanField(default=False)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="crm.branch"
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.child",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Funnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("CONSTRUCTION", "Строительство"),
                            ("MANAGEMENT", "Управление"),
                            ("BIART_RENTAL", "Аренда зала BIART"),
                        ],
                        max_length=30,
                    ),
                ),
                ("contact_person", models.CharField(max_length=200)),
                ("contact_phone", models.CharField(max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("bin_number", models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Администратор"),
                            ("sales_head", "Руководитель продаж"),
                            ("rm", "Региональный менеджер"),
                            ("manager", "Менеджер филиала"),
                            ("sales", "Менеджер по продажам"),
                            ("sales_assistant", "Ассистент продаж"),
                            ("network_coordinator", "Координатор сети"),
                            ("hr", "HR"),
                            ("site", "Системный"),
                        ],
                        max_length=30,
                    ),
                ),
                ("branches", models.ManyToManyField(blank=True, to="crm.branch")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("due_date", models.DateField()),
                ("is_done", models.BooleanField(default=False)),
                ("auto_generated", models.BooleanField(default=False)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="crm.deal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("grade_band", models.CharField(blank=True, max_length=30)),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "entrance_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("installments_count", models.PositiveIntegerField(default=1)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.branch"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField()),
                ("color", models.CharField(default="#94A3B8", max_length=7)),
                ("is_won", models.BooleanField(default=False)),
                ("is_lost", models.BooleanField(default=False)),
                (
                    "funnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="crm.funnel",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("due_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_schedules",
                        to="crm.deal",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="deal",
            name="funnel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="crm.funnel"
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.contact",
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.partner",
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="crm.stage"
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="tariff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.tariff",
            ),
        ),
        migrations.CreateModel(
            name="ClassQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_or_group", models.CharField(max_length=30)),
                ("capacity", models.PositiveIntegerField()),
                ("occupied", models.PositiveIntegerField(default=0)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.branch"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="child",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="crm.contact",
            ),
        ),
        migrations.CreateModel(
            name="BotMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("BOT", "Бот"), ("CLIENT", "Клиент")], max_length=20
                    ),
                ),
                ("text", models.TextField()),
                ("field_filled", models.CharField(blank=True, max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_messages",
                        to="crm.deal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BOT_MESSAGE", "Бот"),
                            ("CALL", "Звонок"),
                            ("WHATSAPP", "WhatsApp"),
                            ("SYSTEM", "Система"),
                            ("TASK", "Задача"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        choices=[
                            ("BOT", "Бот"),
                            ("MANAGER", "Менеджер"),
                            ("SYSTEM", "Система"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="crm.deal",
                    ),
                ),
            ],
        ),
    ]
